#!/bin/bash

python3 manage.py makemigrations users --settings=settings.production;
python3 manage.py makemigrations sc --settings=settings.production;
python3 manage.py makemigrations --settings=settings.production;
python3 manage.py migrate --settings=settings.production;
python3 manage.py pop --settings=settings.production;
